const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..');let checks=0;
const elements=new Map();let monthButtons=[];
class Element{constructor(id){this.id=id;this.listeners={};this.attributes={};this.dataset={};this.value='';this.hidden=false;this.open=false;this._html='';this.textContent='';}set innerHTML(v){this._html=v;if(this.id==='month-nav'){monthButtons=[...v.matchAll(/data-month="([^"]+)" aria-pressed="([^"]+)"/g)].map(m=>{const e=new Element('month-'+m[1]);e.dataset.month=m[1];e.attributes['aria-pressed']=m[2];return e;});}}get innerHTML(){return this._html}setAttribute(k,v){this.attributes[k]=v}addEventListener(t,f){this.listeners[t]=f}focus(){document.activeElement=this}click(){document.listeners.click({target:{closest:s=>s==='[data-month]'?this:null}})}querySelectorAll(){return monthButtons}showModal(){this.open=true}close(){this.open=false;this.listeners.close?.()}getBoundingClientRect(){return {left:0,right:600,top:0,bottom:400}}}
const document={activeElement:null,listeners:{},getElementById(id){if(!elements.has(id))elements.set(id,new Element(id));return elements.get(id)},querySelectorAll(){return monthButtons},addEventListener(t,f){this.listeners[t]=f},contains:e=>!!e};const location={hash:''},history={replaceState(a,b,h){location.hash=h},pushState(a,b,h){location.hash=h}};const sandbox={window:{addEventListener(){}},document,location,history,Intl,Date,console,encodeURIComponent,decodeURIComponent};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(root,'data.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(root,'artifacts.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),sandbox);
const {entries,months}=sandbox.window.ARCADE_DATA,A=sandbox.window.Arcade,$=id=>document.getElementById(id);function check(n,fn){fn();checks++;console.log('PASS '+n)};
check('49 unique entries, 18 projects, January–October coverage',()=>{assert.equal(entries.length,49);assert.equal(new Set(entries.map(e=>e.id)).size,49);assert.equal(entries.filter(e=>e.type==='Project').length,18);assert.equal(new Set(entries.map(e=>e.date.slice(0,7))).size,10)});
check('Known duplicates merged, all 34 early activities retained',()=>{for(const id of ['jul-dojo','jul-animals','jul-map'])assert(!entries.some(e=>e.id===id));assert.equal(entries.filter(e=>e.type!=='Project').length,31);for(const id of ['digital-dojo','animal-adventure','park-map'])assert(entries.some(e=>e.id===id))});
check('Initial cards, honest counts, and newest-first sorting',()=>{assert.equal(($('results').innerHTML.match(/<article /g)||[]).length,49);assert.equal($('total-count').textContent,49);assert.equal(A.selectEntries()[0].date,'2026-10-06');assert.equal($('empty-state').hidden,true)});
check('275 month/topic/type combinations match data exactly',()=>{for(const month of ['all',...months.map(m=>m.id)])for(const topic of ['all','Everyday','Learning & play','Making things','Writing & teaching'])for(const type of ['all','Project','Saved artifact','Draft','Conversation']){const s={month,topic,type,query:'',view:'grid'},expected=entries.filter(e=>(month==='all'||e.date.startsWith(month))&&(topic==='all'||e.themes.includes(topic))&&(type==='all'||e.type===type));assert.equal(A.selectEntries(s).length,expected.length)}});
check('Search handles case, Unicode, title, topic, and no matches',()=>{const s={month:'all',topic:'all',type:'all',query:'pOkÉmOn',view:'grid'};assert(A.selectEntries(s).length>=5);assert.equal(A.selectEntries({...s,query:'zz-no-such-entry'}).length,0);assert(A.selectEntries({...s,query:'cooking'}).length>0)});
check('Empty state, reset, and search input',()=>{$('search').listeners.input({target:{value:'zz-no-such-entry'}});assert.equal($('empty-state').hidden,false);assert.equal($('clear-filters').hidden,false);A.resetFilters();assert.equal($('empty-state').hidden,true);assert.equal($('clear-filters').hidden,true);assert.equal($('search').value,'')});
check('Timeline groups all ten months chronologically',()=>{$('timeline-view').listeners.click();assert.equal(($('results').innerHTML.match(/class="timeline-section"/g)||[]).length,10);assert.equal(A.selectEntries()[0].date,'2026-01-12');assert.equal($('timeline-view').attributes['aria-pressed'],'true')});
check('Month controls support End, Home and arrow navigation',()=>{monthButtons[1].focus();$('month-nav').listeners.keydown({key:'End',preventDefault(){}});assert.equal(A.state.month,'2026-10');assert.equal(document.activeElement.dataset.month,'2026-10');$('month-nav').listeners.keydown({key:'Home',preventDefault(){}});assert.equal(A.state.month,'all');$('month-nav').listeners.keydown({key:'ArrowRight',preventDefault(){}});assert.equal(A.state.month,'2026-01')});
check('Detail dialog uses real entry, public links, and restores focus',()=>{const prior=document.activeElement;A.openEntry('ai-adoption');assert.equal($('entry-dialog').open,true);assert.match($('dialog-content').innerHTML,/https:\/\/state-of-ai-adoption\.sylar0706\.chatgpt\.site/);assert.equal(location.hash,'#entry-ai-adoption');A.closeEntry();assert.equal($('entry-dialog').open,false);assert.equal(document.activeElement,prior)});
check('Private prototypes have no private URL and invalid IDs do nothing',()=>{A.openEntry('digital-dojo');assert(!$('dialog-content').innerHTML.includes('digital-dojo.sylar'));assert.match($('dialog-content').innerHTML,/source app remains private/);A.closeEntry();A.openEntry('msrp-finder');assert.match($('dialog-content').innerHTML,/Original artifact not yet available/);A.closeEntry();A.openEntry('unknown');assert.equal($('entry-dialog').open,false)});
check('Public link allowlist has precisely three verified destinations',()=>{assert.equal(JSON.stringify(entries.filter(e=>e.publicUrl).map(e=>e.publicUrl).sort()),JSON.stringify(['https://github.com/soonenator/Pkmncenter','https://starter-partner-quiz.sylar0706.chatgpt.site','https://state-of-ai-adoption.sylar0706.chatgpt.site'].sort()))});
check('No private identifiers, transcript links, credentials, or inventory content deployed',()=>{const source=['index.html','app.js','data.js','artifacts.js','styles.css'].map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n');for(const pattern of [/libfile_/i,/appgprj_/i,/chatgpt\.com\/c\//i,/nicholasjsoon@/i,/dream_notes/i,/action_items/i,/agent_notes/i,/Bearer\s+[A-Za-z0-9]/,/api[_-]?key\s*[:=]/i])assert(!pattern.test(source),String(pattern));assert(!source.includes('portfolio-inventory'));});
check('HTML local assets resolve; responsive/reduced-motion and accessibility hooks exist',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const match of html.matchAll(/(?:href|src)="([^"#]+)"/g)){if(!/^https?:/.test(match[1]))assert(fs.existsSync(path.join(root,match[1])),match[1])}assert(html.includes('aria-live="polite"'));assert(html.includes('aria-labelledby="detail-title"'));assert(html.includes('name="viewport"'));const css=fs.readFileSync(path.join(root,'styles.css'),'utf8');assert(css.includes('prefers-reduced-motion'));assert(css.includes('@media(max-width:620px)'));assert(css.includes(':focus-visible'));assert(!css.includes('@import'))});
check('Companion label text has explicit dark contrast',()=>{assert(fs.readFileSync(path.join(root,'styles.css'),'utf8').includes('.companion-label{color:var(--ink);'))});
check('NickSoon AI Journey branding replaces the prior site name',()=>{for(const name of ['index.html','data.js','README.md']){const s=fs.readFileSync(path.join(root,name),'utf8');assert(s.includes('NickSoon AI Journey'));assert(!s.includes('SideQuestSoon'));}assert(!fs.readFileSync(path.join(root,'index.html'),'utf8').includes('AI ARCADE'));});
check('Every artifact is original, typed, and served from a valid file or verified public destination',()=>{
  const permitted=new Set([...entries.filter(e=>e.publicUrl).map(e=>e.publicUrl),'https://soonenator.github.io/Pkmncenter/','https://martial-atlas-fresh.vercel.app/','https://claude-martialarts-test.vercel.app/']);
  for(const [id,items] of Object.entries(sandbox.window.ARCADE_ARTIFACTS)) {
    assert(entries.some(e=>e.id===id),id);assert(items.length>0,id);
    for(const item of items){assert(['image','html','pdf','link'].includes(item.kind));assert(item.title);assert(item.caption);
      if(item.kind==='link')assert(permitted.has(item.src),item.src);
      else assert(fs.existsSync(path.join(root,item.src)),item.src);
      if(item.preview)assert(fs.existsSync(path.join(root,item.preview)),item.preview);
      if(item.kind==='image')assert(item.alt,id+' needs alternative text');
      if(item.kind==='pdf')assert(item.preview,id+' needs a visible preview');
      if(item.download)assert(item.src.startsWith('assets/'));
    }
  }
});
check('Cards distinguish real artifact access from story-only entries',()=>{A.resetFilters();assert.match($('results').innerHTML,/View the work/);assert.match($('results').innerHTML,/Read the story/);A.openEntry('porygongpt');assert.match($('dialog-content').innerHTML,/Open full-size image/);assert.match($('dialog-content').innerHTML,/Download image/);assert.match($('dialog-content').innerHTML,/Animation preview/);A.closeEntry();});
check('Embeds are local and sandboxed, external sites use explicit outbound links',()=>{const app=fs.readFileSync(path.join(root,'app.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert(app.includes('sandbox="allow-scripts"'));assert(!app.includes('allow-same-origin'));assert(html.includes("frame-src 'self'"));assert(html.includes("connect-src 'none'"));});
check('All archived HTML is standalone, dated, private-data-free, and syntactically valid',()=>{
  for(const file of fs.readdirSync(path.join(root,'assets/artifacts')).filter(f=>f.endsWith('.html'))){
    const content=fs.readFileSync(path.join(root,'assets/artifacts',file),'utf8');
    assert(content.includes('Archived artifact'),file);assert(content.includes("connect-src 'none'"),file);
    for(const code of content.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi))new vm.Script(code[1],{filename:file});
    for(const forbidden of [/libfile_/i,/chatgpt\.com\/c\//i,/nicholasjsoon@/i,/localStorage/,/fetch\s*\(/,/XMLHttpRequest/,/WebSocket/])assert(!forbidden.test(content),file+' '+forbidden);
  }
});
check('Closing a dialog removes its artifact media',()=>{A.openEntry('animal-adventure');assert.match($('dialog-content').innerHTML,/<iframe/);A.closeEntry();assert.equal($('dialog-content').innerHTML,'');});
console.log(`${checks} checks passed. Logic/static verification only; no browser rendering or assistive-technology test.`);
